/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Buildings.glb --transform
Author: Robin Butler (https://sketchfab.com/StarTrekGuy)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/stylized-low-poly-sci-fi-buildings-701381fef32444e79ad804315e563049
Title: Stylized Low Poly Sci-Fi Buildings
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Buildings(props) {
  const { nodes, materials } = useGLTF('./models/Buildings-transformed.glb');
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <group position={[0, 0, 0.99]} scale={[1, 1.48, 0.57]}>
          <mesh geometry={nodes.Cube_0.geometry} material={materials.Grey_Light}>
                          <meshStandardMaterial color="grey" />

        </mesh>
 
          <mesh geometry={nodes.Cube_1.geometry} material={materials.Grey_Dark} />
          <mesh geometry={nodes.Cube_2.geometry} material={materials.Tan_Grey} />
          <mesh geometry={nodes.Cube_3.geometry} material={materials.Glow} />
        </group>
        <group position={[0, 0, 0.99]} scale={[1, 1.48, 0.57]}>
          <mesh geometry={nodes.Cube001_0.geometry} material={materials.Grey_Light} />
          <mesh geometry={nodes.Cube001_1.geometry} material={materials.Grey_Dark} />
          <mesh geometry={nodes.Cube001_2.geometry} material={materials.Glow}>
              <meshStandardMaterial color="orange" />
        </mesh>
        </group>
        <group position={[0, 0, 0.99]} scale={[1, 1.48, 0.57]}>
          <mesh geometry={nodes.Cube002_0.geometry} material={materials.Grey_Dark} />
          <mesh geometry={nodes.Cube002_1.geometry} material={materials.Yellow} />
        </group>
        <mesh geometry={nodes.Plane_0.geometry} material={materials.Ground_Tan} scale={[10.52, 10.52, 1.55]} >
        <meshStandardMaterial color="orange" />
        </mesh>
        <mesh geometry={nodes.Cube003_0.geometry} material={materials.Tan_Grey} position={[0, 0, 0.99]} scale={[1, 1.48, 0.57]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/Buildings-transformed.glb')
